kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  annotations:
    description: Defines how to deploy the application server
    template.alpha.openshift.io/wait-for-ready: 'true'
  name: httpd-example
  labels:
    app: httpd-example
    template: httpd-example
spec:
  strategy:
    type: Rolling
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      timeoutSeconds: 600
      maxUnavailable: 25%
      maxSurge: 25%
    resources: {}
    activeDeadlineSeconds: 21600
  replicas: 1
  revisionHistoryLimit: 10
  test: false
  selector:
    name: httpd-example
  template:
    metadata:
      name: httpd-example
      creationTimestamp: null
      labels:
        name: httpd-example
    spec:
      volumes:
        - name: drtest
          persistentVolumeClaim:
            claimName: drtest
      containers:
        - resources:
            limits:
              memory: 512Mi
          name: httpd-example
####          command: ['sh', '-c' , 'trap exit TERM; while true; do echo $(date) | tee -a /data/drtestfile.txt; sync; sleep 1; done']
          command: ['sh', '-c' , 'trap exit TERM; while true; do echo $(date); sync; sleep 1; done']
          volumeMounts:
            - name: drtest
              mountPath: /data
          image: 'quay.io/leandroberetta/mimik:latest'
