kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: ose3
  namespace: atp
  labels:
    app: ose3
    template: ose3
spec:
  to:
    kind: Service
    name: ose3
    weight: 100
  wildcardPolicy: None
