kind: Service
apiVersion: v1
metadata:
  name: httpd-example
  namespace: atp
  labels:
    app: httpd-example
    template: httpd-example
  annotations:
    description: Exposes and load balances the application pods
spec:
  ports:
    - name: web
      protocol: TCP
      port: 8080
      targetPort: 8080
  internalTrafficPolicy: Cluster
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    name: httpd-example
